<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_56d003cfb84ae',
  'title' => 'Cargonizer API',
  'fields' => array (
    array (
      'key' => 'field_56d00405b1888',
      'label' => 'Api key',
      'name' => 'cargonizer_api_key',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56d0043fb1889',
      'label' => 'Api sender',
      'name' => 'cargonizer_api_sender',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56d0044fb188a',
      'label' => 'Sandbox',
      'name' => 'sandbox',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array(
      'key' => 'field_56d0045eb188b',
      'label' => 'Sandbox api key',
      'name' => 'sandbox_api_key',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),

    array(
      'key' => 'field_56d00469b188c',
      'label' => 'Sandbox api sender',
      'name' => 'sandbox_api_sender',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),

    array(
      'key' => 'field_58ec8df0412a',
      'label' => 'Delivery Company',
      'name' => 'cargonizer_delivery_company',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'choices' => array( 0 => 'null'),
      'default_value' => array(),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),

    array(
      'key' => 'field_58ec92d56985a',
      'label' => 'Services',
      'name' => 'cargonizer_services',
      'type' => 'checkbox',
      'instructions' => 'Select delivery company and update',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'choices' => array(),
      'default_value' => array(),
      'layout' => 'vertical',
      'toggle' => 0,
    ),

  ),
 'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'cargonizer-general-settings',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;

