<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_56cc4de510b34',
  'title' => 'Cargonizer',
  'fields' => array(
    array (
      'key' => 'field_56cc5865b6e45',
      'label' => 'Parcels',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_56cd64c524656',
      'label' => 'Carrier',
      'name' => 'transport_agreement',
      'type' => 'select',
      'instructions' => 'If empty, setup api settings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'choices' => array(0 => 'choose carrier'),
      'default_value' => array(),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 1,
    ),
    array (
      'key' => 'field_56cec446a4498',
      'label' => 'Type',
      'name' => 'parcel_type',
      'type' => 'select',
      'instructions' => 'Velg produkt/tjeneste',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'choices' => array(0 => 'velg type',),
      'default_value' => array(),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_56cead8e7fd30',
      'label' => 'Message',
      'name' => 'message_consignee',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'wpautop',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56cc575e16e1c',
      'label' => 'Packages',
      'name' => 'items',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => null,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Add Row',
      'sub_fields' => array (
        array(
          'key' => 'field_56cc57fcd9178',
          'label' => 'Count',
          'name' => 'parcel_amount',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array('width' => '','class' => '', 'id' => '',),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56cec446a4499',
          'label' => 'Type',
          'name' => 'parcel_package_type',
          'type' => 'select',
          'instructions' => 'Set a custom parcel type.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array('width' => '','class' => '','id' => '',),
          'choices' => array(0 => 'velg type',),
          'default_value' => array(),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'placeholder' => '',
          'disabled' => 0,
          'readonly' => 0,
        ),
        array (
          'key' => 'field_56cc578216e1d',
          'label' => 'Description',
          'name' => 'parcel_description',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56cc4de94d2c6',
          'label' => 'Weight (kg)',
          'name' => 'parcel_weight',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56cc4e196d60a',
          'label' => 'Height (cm)',
          'name' => 'parcel_height',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array(
          'key' => 'field_56cc4dfc6d608',
          'label' => 'Length (cm)',
          'name' => 'parcel_length',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array('width' => '','class' => '','id' => '',),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array(
          'key' => 'field_56cc4e0a6d609',
          'label' => 'Width (cm)',
          'name' => 'parcel_width',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array('width' => '','class' => '','id' => '',),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array(
      'key' => 'field_56cd6cad3cbf3',
      'label' => 'Opprett oppdrag',
      'name' => 'create_consignment',
      'type' => 'true_false',
      'instructions' => 'Kryss av denne sjekkboksen når du har valgt leverandør og lagt inn pakke(r)',
      'required' => 0,
      'conditional_logic' => null,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'message' => '',
      'default_value' => 0,
    ),
    array(
      'key' => 'field_56cee5f87deaa',
      'label' => 'Bekreftelse',
      'name' => 'bekreftelse',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_56cee60ac7cd0',
      'label' => 'Dato',
      'name' => 'consignment_created_at',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 0,
    ),
    array(
      'key' => 'field_56cee621c7cd1',
      'label' => 'Consignment id',
      'name' => 'consignment_id',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 0,
    ),
    array(
      'key' => 'field_56cee62ec7cd2',
      'label' => 'Sporingskode',
      'name' => 'consignment_tracking_code',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 0,
    ),
    array(
      'key' => 'field_56cee6bd6fb1e',
      'label' => 'Sporings-adresse',
      'name' => 'consignment_tracking_url',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56cee6476fb1d',
      'label' => 'Consignment pdf',
      'name' => 'consignment_pdf',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array('width' => '','class' => '','id' => '',),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 0,
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'shop_order',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;